architecture: replication
auth:
  rootPassword: "REPLACE_WITH_SECURE_PASSWORD"
  database: my-app-db
  username: "REPLACE_WITH_USERNAME"
  password: "REPLACE_WITH_SECURE_PASSWORD"
# enable init container that changes the owner and group of the persistent volume mountpoint to runAsUser:fsGroup
volumePermissions:
  enabled: true
secondary:
  replicaCount: 1
  persistence:
    accessModes: ["ReadWriteOnce"]
    # storage class for LKE volumes
    storageClass: linode-block-storage
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    labels:
      release: monitoring-stack
