apiVersion: v1
kind: Secret
metadata:
  name: slack-auth
  namespace: monitoring
type: Opaque
stringData:
  webhook: "https://hooks.slack.com/services/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"
