apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-controller-config
  namespace: monitoring
controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      labels:
        release: monitoring-stack
